# Generated by Django 4.0.5 on 2022-07-02 03:38

import autoslug.fields
from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('des', models.TextField(max_length=1000)),
                ('bdes', models.TextField(max_length=3000)),
                ('content', froala_editor.fields.FroalaField()),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=8000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_title', models.CharField(max_length=50)),
                ('ev_des', models.TextField(max_length=3000)),
                ('ev_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='ev_title', unique=True)),
                ('ev_content', froala_editor.fields.FroalaField()),
                ('ev_img', models.ImageField(upload_to='ev_images')),
            ],
        ),
    ]
