# Generated by Django 4.0.5 on 2022-07-02 07:37

import autoslug.fields
from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_title', models.CharField(max_length=50)),
                ('n_des', models.TextField(max_length=3000)),
                ('n_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='ev_title', unique=True)),
                ('n_content', froala_editor.fields.FroalaField()),
                ('n_img', models.ImageField(upload_to='news_images')),
            ],
        ),
    ]
